// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type CaptchaResp struct {
	BaseResp
	Data CaptchaVo `json:"data,omitempty"`
}

type CaptchaVo struct {
	CaptchaEnabled bool   `json:"captchaEnabled"` // 是否开启验证码
	Uuid           string `json:"uuid,omitempty"` // 唯一标识
	Img            string `json:"img,omitempty"`  // 验证码图片（base64）
}

type LoginReq struct {
	ClientId  string `json:"clientId"`           // 客户端id（必填）
	GrantType string `json:"grantType"`          // 授权类型（必填）
	TenantId  string `json:"tenantId,omitempty"` // 租户ID
	Code      string `json:"code,omitempty"`     // 验证码
	Uuid      string `json:"uuid,omitempty"`     // 验证码唯一标识
	Username  string `json:"username,omitempty"` // 用户名
	Password  string `json:"password,omitempty"` // 密码
}

type LoginResp struct {
	BaseResp
	Data LoginVo `json:"data,omitempty"`
}

type LoginTenantVo struct {
	TenantEnabled bool           `json:"tenantEnabled"`    // 租户开关
	VoList        []TenantListVo `json:"voList,omitempty"` // 租户对象列表
}

type LoginVo struct {
	AccessToken     string `json:"access_token"`        // 授权令牌
	RefreshToken    string `json:"refresh_token"`       // 刷新令牌
	ExpireIn        int64  `json:"expire_in"`           // 授权令牌有效期（秒）
	RefreshExpireIn int64  `json:"refresh_expire_in"`   // 刷新令牌有效期（秒）
	Scope           string `json:"scope,omitempty"`     // 令牌权限
	Openid          string `json:"openid,omitempty"`    // 用户 openid
	ClientId        string `json:"client_id,omitempty"` // 应用id
}

type TenantListResp struct {
	BaseResp
	Data LoginTenantVo `json:"data,omitempty"`
}

type TenantListVo struct {
	TenantId    string `json:"tenantId"`    // 租户编号
	CompanyName string `json:"companyName"` // 企业名称
	Domain      string `json:"domain"`      // 域名
}
