// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type BaseResp struct {
	Code int32  `json:"code"`
	Msg  string `json:"msg"`
}

type CaptchaResp struct {
	BaseResp
	Data CaptchaVo `json:"data,omitempty"`
}

type CaptchaVo struct {
	CaptchaEnabled bool   `json:"captchaEnabled"` // 是否开启验证码
	Uuid           string `json:"uuid,omitempty"` // 唯一标识
	Img            string `json:"img,omitempty"`  // 验证码图片（base64）
}

type ConfigGetByKeyReq struct {
	ConfigKey string `path:"configKey"` // 参数键名
}

type ConfigGetInfoReq struct {
	ConfigId int64 `path:"configId"` // 参数主键
}

type ConfigRemoveReq struct {
	ConfigIds string `path:"configIds"` // 参数ID串（逗号分隔）
}

type ConfigReq struct {
	ConfigId    int64  `json:"configId,omitempty"`   // 参数主键
	ConfigName  string `json:"configName"`           // 参数名称
	ConfigKey   string `json:"configKey"`            // 参数键名
	ConfigValue string `json:"configValue"`          // 参数键值
	ConfigType  string `json:"configType,omitempty"` // 系统内置（Y是 N否）
	Remark      string `json:"remark,omitempty"`     // 备注
}

type ConfigResp struct {
	BaseResp
	Data ConfigVo `json:"data,omitempty"`
}

type ConfigValueResp struct {
	BaseResp
	Data string `json:"data,omitempty"` // 参数键值
}

type ConfigVo struct {
	ConfigId    int64  `json:"configId"`    // 参数主键
	ConfigName  string `json:"configName"`  // 参数名称
	ConfigKey   string `json:"configKey"`   // 参数键名
	ConfigValue string `json:"configValue"` // 参数键值
	ConfigType  string `json:"configType"`  // 系统内置（Y是 N否）
	Remark      string `json:"remark"`      // 备注
	CreateTime  string `json:"createTime"`  // 创建时间
}

type DictDataByTypeReq struct {
	DictType string `path:"dictType"` // 字典类型
}

type DictDataGetInfoReq struct {
	DictCode int64 `path:"dictCode"` // 字典编码
}

type DictDataListResp struct {
	BaseResp
	Data []DictDataVo `json:"data"`
}

type DictDataRemoveReq struct {
	DictCodes string `path:"dictCodes"` // 字典编码串（逗号分隔）
}

type DictDataReq struct {
	DictCode  int64  `json:"dictCode,omitempty"`  // 字典编码
	DictSort  int32  `json:"dictSort"`            // 字典排序
	DictLabel string `json:"dictLabel"`           // 字典标签
	DictValue string `json:"dictValue"`           // 字典键值
	DictType  string `json:"dictType"`            // 字典类型
	CssClass  string `json:"cssClass,omitempty"`  // 样式属性
	ListClass string `json:"listClass,omitempty"` // 表格回显样式
	IsDefault string `json:"isDefault,omitempty"` // 是否默认（Y是 N否）
	Remark    string `json:"remark,omitempty"`    // 备注
}

type DictDataResp struct {
	BaseResp
	Data DictDataVo `json:"data,omitempty"`
}

type DictDataVo struct {
	DictCode   int64  `json:"dictCode"`   // 字典编码
	DictSort   int32  `json:"dictSort"`   // 字典排序
	DictLabel  string `json:"dictLabel"`  // 字典标签
	DictValue  string `json:"dictValue"`  // 字典键值
	DictType   string `json:"dictType"`   // 字典类型
	CssClass   string `json:"cssClass"`   // 样式属性
	ListClass  string `json:"listClass"`  // 表格回显样式
	IsDefault  string `json:"isDefault"`  // 是否默认（Y是 N否）
	Remark     string `json:"remark"`     // 备注
	CreateTime string `json:"createTime"` // 创建时间
}

type DictTypeGetInfoReq struct {
	DictId int64 `path:"dictId"` // 字典主键
}

type DictTypeListResp struct {
	BaseResp
	Data []DictTypeVo `json:"data"`
}

type DictTypeRemoveReq struct {
	DictIds string `path:"dictIds"` // 字典ID串（逗号分隔）
}

type DictTypeReq struct {
	DictId   int64  `json:"dictId,omitempty"` // 字典主键
	DictName string `json:"dictName"`         // 字典名称
	DictType string `json:"dictType"`         // 字典类型
	Remark   string `json:"remark,omitempty"` // 备注
}

type DictTypeResp struct {
	BaseResp
	Data DictTypeVo `json:"data,omitempty"`
}

type DictTypeVo struct {
	DictId     int64  `json:"dictId"`     // 字典主键
	DictName   string `json:"dictName"`   // 字典名称
	DictType   string `json:"dictType"`   // 字典类型
	Remark     string `json:"remark"`     // 备注
	CreateTime string `json:"createTime"` // 创建时间
}

type LoginReq struct {
	ClientId  string `json:"clientId"`           // 客户端id（必填）
	GrantType string `json:"grantType"`          // 授权类型（必填）
	TenantId  string `json:"tenantId,omitempty"` // 租户ID
	Code      string `json:"code,omitempty"`     // 验证码
	Uuid      string `json:"uuid,omitempty"`     // 验证码唯一标识
	Username  string `json:"username,omitempty"` // 用户名
	Password  string `json:"password,omitempty"` // 密码
}

type LoginResp struct {
	BaseResp
	Data LoginVo `json:"data,omitempty"`
}

type LoginTenantVo struct {
	TenantEnabled bool           `json:"tenantEnabled"`    // 租户开关
	VoList        []TenantListVo `json:"voList,omitempty"` // 租户对象列表
}

type LoginVo struct {
	AccessToken     string `json:"access_token"`        // 授权令牌
	RefreshToken    string `json:"refresh_token"`       // 刷新令牌
	ExpireIn        int64  `json:"expire_in"`           // 授权令牌有效期（秒）
	RefreshExpireIn int64  `json:"refresh_expire_in"`   // 刷新令牌有效期（秒）
	Scope           string `json:"scope,omitempty"`     // 令牌权限
	Openid          string `json:"openid,omitempty"`    // 用户 openid
	ClientId        string `json:"client_id,omitempty"` // 应用id
}

type MetaVo struct {
	Title   string `json:"title,omitempty"`   // 设置该路由在侧边栏和面包屑中展示的名字
	Icon    string `json:"icon,omitempty"`    // 设置该路由的图标，对应路径src/assets/icons/svg
	NoCache bool   `json:"noCache,omitempty"` // 设置为true，则不会被 <keep-alive>缓存
	Link    string `json:"link,omitempty"`    // 内链地址（http(s)://开头）
	Remark  string `json:"remark,omitempty"`  // 备注
}

type RouterResp struct {
	BaseResp
	Data []RouterVo `json:"data"`
}

type RouterVo struct {
	Name       string     `json:"name,omitempty"`       // 路由名字
	Path       string     `json:"path,omitempty"`       // 路由地址
	Hidden     bool       `json:"hidden,omitempty"`     // 是否隐藏路由
	Redirect   string     `json:"redirect,omitempty"`   // 重定向地址
	Component  string     `json:"component,omitempty"`  // 组件地址
	Query      string     `json:"query,omitempty"`      // 路由参数
	AlwaysShow bool       `json:"alwaysShow,omitempty"` // 是否总是显示
	Meta       MetaVo     `json:"meta,omitempty"`       // 其他元素
	Children   []RouterVo `json:"children,omitempty"`   // 子路由
}

type SysRoleVo struct {
	RoleId     int64  `json:"roleId"`     // 角色ID
	RoleName   string `json:"roleName"`   // 角色名称
	RoleKey    string `json:"roleKey"`    // 角色权限字符串
	RoleSort   int32  `json:"roleSort"`   // 显示顺序
	DataScope  string `json:"dataScope"`  // 数据范围
	Status     string `json:"status"`     // 角色状态（0正常 1停用）
	Remark     string `json:"remark"`     // 备注
	CreateTime string `json:"createTime"` // 创建时间
}

type SysUserVo struct {
	UserId      int64       `json:"userId"`      // 用户ID
	TenantId    string      `json:"tenantId"`    // 租户ID
	DeptId      int64       `json:"deptId"`      // 部门ID
	UserName    string      `json:"userName"`    // 用户账号
	NickName    string      `json:"nickName"`    // 用户昵称
	UserType    string      `json:"userType"`    // 用户类型（sys_user系统用户）
	Email       string      `json:"email"`       // 用户邮箱
	Phonenumber string      `json:"phonenumber"` // 手机号码
	Sex         string      `json:"sex"`         // 用户性别（0男 1女 2未知）
	Avatar      int64       `json:"avatar"`      // 头像地址
	Status      string      `json:"status"`      // 帐号状态（0正常 1停用）
	LoginIp     string      `json:"loginIp"`     // 最后登录IP
	LoginDate   string      `json:"loginDate"`   // 最后登录时间
	Remark      string      `json:"remark"`      // 备注
	CreateTime  string      `json:"createTime"`  // 创建时间
	DeptName    string      `json:"deptName"`    // 部门名
	Roles       []SysRoleVo `json:"roles"`       // 角色对象
}

type TableDataInfo struct {
	Total int64       `json:"total"` // 总记录数
	Rows  interface{} `json:"rows"`  // 列表数据
}

type TableDataInfoResp struct {
	BaseResp
	Data TableDataInfo `json:"data,omitempty"`
}

type TenantListResp struct {
	BaseResp
	Data LoginTenantVo `json:"data,omitempty"`
}

type TenantListVo struct {
	TenantId    string `json:"tenantId"`    // 租户编号
	CompanyName string `json:"companyName"` // 企业名称
	Domain      string `json:"domain"`      // 域名
}

type UserInfoResp struct {
	BaseResp
	Data UserInfoVo `json:"data,omitempty"`
}

type UserInfoVo struct {
	User        SysUserVo `json:"user"`        // 用户基本信息
	Permissions []string  `json:"permissions"` // 菜单权限
	Roles       []string  `json:"roles"`       // 角色权限
}
