###
GET {{baseUrl}}/system/menu/getRouters
Authorization: {{jwtToken}}
clientid: {{clientid}}
Content-Type: application/json;charset=UTF-8

###
GET {{baseUrl}}/system/user/getInfo
Authorization: {{jwtToken}}
clientid: {{clientid}}
Content-Type: application/json;charset=UTF-8


###
GET {{baseUrl}}/system/dict/data/type/sys_yes_no
Authorization: {{jwtToken}}
clientid: {{clientid}}
Content-Type: application/json;charset=UTF-8

###
GET {{baseUrl}}/system/config/list?pageNum=1&pageSize=10
Authorization: {{jwtToken}}
clientid: {{clientid}}
Content-Type: application/json;charset=UTF-8

###
GET {{baseUrl}}/system/dict/data/list?pageNum=1&pageSize=10&dictType=sys_yes_no
Authorization: {{jwtToken}}
clientid: {{clientid}}
Content-Type: application/json;charset=UTF-8
###

###
GET {{baseUrl}}/system/user/deptTree
Authorization: {{jwtToken}}
clientid: {{clientid}}
Content-Type: application/json;charset=UTF-8
###
###
GET {{baseUrl}}/system/post/deptTree
Authorization: {{jwtToken}}
clientid: {{clientid}}
Content-Type: application/json;charset=UTF-8
###

###
GET {{baseUrl}}/monitor/logininfor/list?pageNum=1&pageSize=10&orderByColumn=loginTime&isAsc=descending
Authorization: {{jwtToken}}
clientid: {{clientid}}
Content-Type: application/json;charset=UTF-8
###