// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	auth "gozero-ruoyi-vue-plus/internal/handler/auth"
	sys "gozero-ruoyi-vue-plus/internal/handler/sys"
	"gozero-ruoyi-vue-plus/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 生成验证码，返回4位数字验证码图片和唯一标识
				Method:  http.MethodGet,
				Path:    "/code",
				Handler: auth.GetCodeHandler(serverCtx),
			},
			{
				// 登录方法，支持密码登录等授权类型
				Method:  http.MethodPost,
				Path:    "/login",
				Handler: auth.LoginHandler(serverCtx),
			},
			{
				// 退出登录
				Method:  http.MethodPost,
				Path:    "/logout",
				Handler: auth.LogoutHandler(serverCtx),
			},
			{
				// 登录页面租户下拉框，获取可用租户列表
				Method:  http.MethodGet,
				Path:    "/tenant/list",
				Handler: auth.TenantListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/auth"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 新增客户端管理
				Method:  http.MethodPost,
				Path:    "/client",
				Handler: sys.ClientAddHandler(serverCtx),
			},
			{
				// 修改客户端管理
				Method:  http.MethodPut,
				Path:    "/client",
				Handler: sys.ClientEditHandler(serverCtx),
			},
			{
				// 查询客户端管理详细
				Method:  http.MethodGet,
				Path:    "/client/:id",
				Handler: sys.ClientGetInfoHandler(serverCtx),
			},
			{
				// 删除客户端管理
				Method:  http.MethodDelete,
				Path:    "/client/:ids",
				Handler: sys.ClientRemoveHandler(serverCtx),
			},
			{
				// 状态修改
				Method:  http.MethodPut,
				Path:    "/client/changeStatus",
				Handler: sys.ClientChangeStatusHandler(serverCtx),
			},
			{
				// 导出客户端管理列表
				Method:  http.MethodPost,
				Path:    "/client/export",
				Handler: sys.ClientExportHandler(serverCtx),
			},
			{
				// 查询客户端管理列表
				Method:  http.MethodGet,
				Path:    "/client/list",
				Handler: sys.ClientListHandler(serverCtx),
			},
			{
				// 新增参数配置
				Method:  http.MethodPost,
				Path:    "/config",
				Handler: sys.ConfigAddHandler(serverCtx),
			},
			{
				// 修改参数配置
				Method:  http.MethodPut,
				Path:    "/config",
				Handler: sys.ConfigEditHandler(serverCtx),
			},
			{
				// 查询参数配置详细
				Method:  http.MethodGet,
				Path:    "/config/:configId",
				Handler: sys.ConfigGetInfoHandler(serverCtx),
			},
			{
				// 删除参数配置
				Method:  http.MethodDelete,
				Path:    "/config/:configIds",
				Handler: sys.ConfigRemoveHandler(serverCtx),
			},
			{
				// 根据参数键名查询参数值
				Method:  http.MethodGet,
				Path:    "/config/configKey/:configKey",
				Handler: sys.ConfigGetByKeyHandler(serverCtx),
			},
			{
				// 导出参数配置列表
				Method:  http.MethodPost,
				Path:    "/config/export",
				Handler: sys.ConfigExportHandler(serverCtx),
			},
			{
				// 查询参数配置列表
				Method:  http.MethodGet,
				Path:    "/config/list",
				Handler: sys.ConfigListHandler(serverCtx),
			},
			{
				// 刷新参数缓存
				Method:  http.MethodDelete,
				Path:    "/config/refreshCache",
				Handler: sys.ConfigRefreshCacheHandler(serverCtx),
			},
			{
				// 根据参数键名修改参数配置
				Method:  http.MethodPut,
				Path:    "/config/updateByKey",
				Handler: sys.ConfigUpdateByKeyHandler(serverCtx),
			},
			{
				// 新增部门
				Method:  http.MethodPost,
				Path:    "/dept",
				Handler: sys.DeptAddHandler(serverCtx),
			},
			{
				// 修改部门
				Method:  http.MethodPut,
				Path:    "/dept",
				Handler: sys.DeptEditHandler(serverCtx),
			},
			{
				// 查询部门详细
				Method:  http.MethodGet,
				Path:    "/dept/:deptId",
				Handler: sys.DeptGetInfoHandler(serverCtx),
			},
			{
				// 删除部门
				Method:  http.MethodDelete,
				Path:    "/dept/:deptId",
				Handler: sys.DeptRemoveHandler(serverCtx),
			},
			{
				// 查询部门列表
				Method:  http.MethodGet,
				Path:    "/dept/list",
				Handler: sys.DeptListHandler(serverCtx),
			},
			{
				// 查询部门列表（排除节点）
				Method:  http.MethodGet,
				Path:    "/dept/list/exclude/:deptId",
				Handler: sys.DeptListExcludeHandler(serverCtx),
			},
			{
				// 获取部门选择框列表
				Method:  http.MethodGet,
				Path:    "/dept/optionselect",
				Handler: sys.DeptOptionSelectHandler(serverCtx),
			},
			{
				// 新增字典数据
				Method:  http.MethodPost,
				Path:    "/dict/data",
				Handler: sys.DictDataAddHandler(serverCtx),
			},
			{
				// 修改字典数据
				Method:  http.MethodPut,
				Path:    "/dict/data",
				Handler: sys.DictDataEditHandler(serverCtx),
			},
			{
				// 查询字典数据详细
				Method:  http.MethodGet,
				Path:    "/dict/data/:dictCode",
				Handler: sys.DictDataGetInfoHandler(serverCtx),
			},
			{
				// 删除字典数据
				Method:  http.MethodDelete,
				Path:    "/dict/data/:dictCodes",
				Handler: sys.DictDataRemoveHandler(serverCtx),
			},
			{
				// 导出字典数据列表
				Method:  http.MethodPost,
				Path:    "/dict/data/export",
				Handler: sys.DictDataExportHandler(serverCtx),
			},
			{
				// 查询字典数据列表
				Method:  http.MethodGet,
				Path:    "/dict/data/list",
				Handler: sys.DictDataListHandler(serverCtx),
			},
			{
				// 根据字典类型查询字典数据
				Method:  http.MethodGet,
				Path:    "/dict/data/type/:dictType",
				Handler: sys.DictDataByTypeHandler(serverCtx),
			},
			{
				// 新增字典类型
				Method:  http.MethodPost,
				Path:    "/dict/type",
				Handler: sys.DictTypeAddHandler(serverCtx),
			},
			{
				// 修改字典类型
				Method:  http.MethodPut,
				Path:    "/dict/type",
				Handler: sys.DictTypeEditHandler(serverCtx),
			},
			{
				// 查询字典类型详细
				Method:  http.MethodGet,
				Path:    "/dict/type/:dictId",
				Handler: sys.DictTypeGetInfoHandler(serverCtx),
			},
			{
				// 删除字典类型
				Method:  http.MethodDelete,
				Path:    "/dict/type/:dictIds",
				Handler: sys.DictTypeRemoveHandler(serverCtx),
			},
			{
				// 导出字典类型列表
				Method:  http.MethodPost,
				Path:    "/dict/type/export",
				Handler: sys.DictTypeExportHandler(serverCtx),
			},
			{
				// 查询字典类型列表
				Method:  http.MethodGet,
				Path:    "/dict/type/list",
				Handler: sys.DictTypeListHandler(serverCtx),
			},
			{
				// 获取字典选择框列表
				Method:  http.MethodGet,
				Path:    "/dict/type/optionselect",
				Handler: sys.DictTypeOptionSelectHandler(serverCtx),
			},
			{
				// 刷新字典缓存
				Method:  http.MethodDelete,
				Path:    "/dict/type/refreshCache",
				Handler: sys.DictTypeRefreshCacheHandler(serverCtx),
			},
			{
				// 获取路由信息
				Method:  http.MethodGet,
				Path:    "/menu/getRouters",
				Handler: sys.GetRoutersHandler(serverCtx),
			},
			{
				// 新增通知公告
				Method:  http.MethodPost,
				Path:    "/notice",
				Handler: sys.NoticeAddHandler(serverCtx),
			},
			{
				// 修改通知公告
				Method:  http.MethodPut,
				Path:    "/notice",
				Handler: sys.NoticeEditHandler(serverCtx),
			},
			{
				// 查询通知公告详细
				Method:  http.MethodGet,
				Path:    "/notice/:noticeId",
				Handler: sys.NoticeGetInfoHandler(serverCtx),
			},
			{
				// 删除通知公告
				Method:  http.MethodDelete,
				Path:    "/notice/:noticeIds",
				Handler: sys.NoticeRemoveHandler(serverCtx),
			},
			{
				// 查询通知公告列表
				Method:  http.MethodGet,
				Path:    "/notice/list",
				Handler: sys.NoticeListHandler(serverCtx),
			},
			{
				// 新增岗位
				Method:  http.MethodPost,
				Path:    "/post",
				Handler: sys.PostAddHandler(serverCtx),
			},
			{
				// 修改岗位
				Method:  http.MethodPut,
				Path:    "/post",
				Handler: sys.PostEditHandler(serverCtx),
			},
			{
				// 查询岗位详细
				Method:  http.MethodGet,
				Path:    "/post/:postId",
				Handler: sys.PostGetInfoHandler(serverCtx),
			},
			{
				// 删除岗位
				Method:  http.MethodDelete,
				Path:    "/post/:postIds",
				Handler: sys.PostRemoveHandler(serverCtx),
			},
			{
				// 导出岗位列表
				Method:  http.MethodPost,
				Path:    "/post/export",
				Handler: sys.PostExportHandler(serverCtx),
			},
			{
				// 查询岗位列表
				Method:  http.MethodGet,
				Path:    "/post/list",
				Handler: sys.PostListHandler(serverCtx),
			},
			{
				// 获取岗位选择框列表
				Method:  http.MethodGet,
				Path:    "/post/optionselect",
				Handler: sys.PostOptionSelectHandler(serverCtx),
			},
			{
				// 获取用户信息
				Method:  http.MethodGet,
				Path:    "/user/getInfo",
				Handler: sys.GetUserInfoHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/system"),
	)
}
