// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDictDataFieldNames          = builder.RawFieldNames(&SysDictData{})
	sysDictDataRows                = strings.Join(sysDictDataFieldNames, ",")
	sysDictDataRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDictDataFieldNames, "`=`"), ",")
	sysDictDataRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDictDataFieldNames, "`dict_code`", "`=`"), "=?,") + "=?"
)

type (
	sysDictDataModel interface {
		Insert(ctx context.Context, data *SysDictData) (sql.Result, error)
		FindOne(ctx context.Context, dictCode int64) (*SysDictData, error)
		Update(ctx context.Context, data *SysDictData) error
		Delete(ctx context.Context, dictCode int64) error
	}

	defaultSysDictDataModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysDictData struct {
		DictCode   int64          `db:"dict_code"`   // 字典编码
		TenantId   string         `db:"tenant_id"`   // 租户编号
		DictSort   int64          `db:"dict_sort"`   // 字典排序
		DictLabel  string         `db:"dict_label"`  // 字典标签
		DictValue  string         `db:"dict_value"`  // 字典键值
		DictType   string         `db:"dict_type"`   // 字典类型
		CssClass   sql.NullString `db:"css_class"`   // 样式属性（其他样式扩展）
		ListClass  sql.NullString `db:"list_class"`  // 表格回显样式
		IsDefault  string         `db:"is_default"`  // 是否默认（Y是 N否）
		CreateDept sql.NullInt64  `db:"create_dept"` // 创建部门
		CreateBy   sql.NullInt64  `db:"create_by"`   // 创建者
		CreateTime sql.NullTime   `db:"create_time"` // 创建时间
		UpdateBy   sql.NullInt64  `db:"update_by"`   // 更新者
		UpdateTime sql.NullTime   `db:"update_time"` // 更新时间
		Remark     sql.NullString `db:"remark"`      // 备注
	}
)

func newSysDictDataModel(conn sqlx.SqlConn) *defaultSysDictDataModel {
	return &defaultSysDictDataModel{
		conn:  conn,
		table: "`sys_dict_data`",
	}
}

func (m *defaultSysDictDataModel) Delete(ctx context.Context, dictCode int64) error {
	query := fmt.Sprintf("delete from %s where `dict_code` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, dictCode)
	return err
}

func (m *defaultSysDictDataModel) FindOne(ctx context.Context, dictCode int64) (*SysDictData, error) {
	query := fmt.Sprintf("select %s from %s where `dict_code` = ? limit 1", sysDictDataRows, m.table)
	var resp SysDictData
	err := m.conn.QueryRowCtx(ctx, &resp, query, dictCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictDataModel) Insert(ctx context.Context, data *SysDictData) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysDictDataRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DictCode, data.TenantId, data.DictSort, data.DictLabel, data.DictValue, data.DictType, data.CssClass, data.ListClass, data.IsDefault, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.Remark)
	return ret, err
}

func (m *defaultSysDictDataModel) Update(ctx context.Context, data *SysDictData) error {
	query := fmt.Sprintf("update %s set %s where `dict_code` = ?", m.table, sysDictDataRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.DictSort, data.DictLabel, data.DictValue, data.DictType, data.CssClass, data.ListClass, data.IsDefault, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.Remark, data.DictCode)
	return err
}

func (m *defaultSysDictDataModel) tableName() string {
	return m.table
}
