// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysSocialFieldNames          = builder.RawFieldNames(&SysSocial{})
	sysSocialRows                = strings.Join(sysSocialFieldNames, ",")
	sysSocialRowsExpectAutoSet   = strings.Join(stringx.Remove(sysSocialFieldNames, "`=`"), ",")
	sysSocialRowsWithPlaceHolder = strings.Join(stringx.Remove(sysSocialFieldNames, "`id`", "`=`"), "=?,") + "=?"
)

type (
	sysSocialModel interface {
		Insert(ctx context.Context, data *SysSocial) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysSocial, error)
		Update(ctx context.Context, data *SysSocial) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysSocialModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysSocial struct {
		Id               int64          `db:"id"`                 // 主键
		UserId           int64          `db:"user_id"`            // 用户ID
		TenantId         string         `db:"tenant_id"`          // 租户id
		AuthId           string         `db:"auth_id"`            // 平台+平台唯一id
		Source           string         `db:"source"`             // 用户来源
		OpenId           sql.NullString `db:"open_id"`            // 平台编号唯一id
		UserName         string         `db:"user_name"`          // 登录账号
		NickName         string         `db:"nick_name"`          // 用户昵称
		Email            string         `db:"email"`              // 用户邮箱
		Avatar           string         `db:"avatar"`             // 头像地址
		AccessToken      string         `db:"access_token"`       // 用户的授权令牌
		ExpireIn         sql.NullInt64  `db:"expire_in"`          // 用户的授权令牌的有效期，部分平台可能没有
		RefreshToken     sql.NullString `db:"refresh_token"`      // 刷新令牌，部分平台可能没有
		AccessCode       sql.NullString `db:"access_code"`        // 平台的授权信息，部分平台可能没有
		UnionId          sql.NullString `db:"union_id"`           // 用户的 unionid
		Scope            sql.NullString `db:"scope"`              // 授予的权限，部分平台可能没有
		TokenType        sql.NullString `db:"token_type"`         // 个别平台的授权信息，部分平台可能没有
		IdToken          sql.NullString `db:"id_token"`           // id token，部分平台可能没有
		MacAlgorithm     sql.NullString `db:"mac_algorithm"`      // 小米平台用户的附带属性，部分平台可能没有
		MacKey           sql.NullString `db:"mac_key"`            // 小米平台用户的附带属性，部分平台可能没有
		Code             sql.NullString `db:"code"`               // 用户的授权code，部分平台可能没有
		OauthToken       sql.NullString `db:"oauth_token"`        // Twitter平台用户的附带属性，部分平台可能没有
		OauthTokenSecret sql.NullString `db:"oauth_token_secret"` // Twitter平台用户的附带属性，部分平台可能没有
		CreateDept       sql.NullInt64  `db:"create_dept"`        // 创建部门
		CreateBy         sql.NullInt64  `db:"create_by"`          // 创建者
		CreateTime       sql.NullTime   `db:"create_time"`        // 创建时间
		UpdateBy         sql.NullInt64  `db:"update_by"`          // 更新者
		UpdateTime       sql.NullTime   `db:"update_time"`        // 更新时间
		DelFlag          string         `db:"del_flag"`           // 删除标志（0代表存在 1代表删除）
	}
)

func newSysSocialModel(conn sqlx.SqlConn) *defaultSysSocialModel {
	return &defaultSysSocialModel{
		conn:  conn,
		table: "`sys_social`",
	}
}

func (m *defaultSysSocialModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysSocialModel) FindOne(ctx context.Context, id int64) (*SysSocial, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysSocialRows, m.table)
	var resp SysSocial
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysSocialModel) Insert(ctx context.Context, data *SysSocial) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysSocialRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.TenantId, data.AuthId, data.Source, data.OpenId, data.UserName, data.NickName, data.Email, data.Avatar, data.AccessToken, data.ExpireIn, data.RefreshToken, data.AccessCode, data.UnionId, data.Scope, data.TokenType, data.IdToken, data.MacAlgorithm, data.MacKey, data.Code, data.OauthToken, data.OauthTokenSecret, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.DelFlag)
	return ret, err
}

func (m *defaultSysSocialModel) Update(ctx context.Context, data *SysSocial) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysSocialRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TenantId, data.AuthId, data.Source, data.OpenId, data.UserName, data.NickName, data.Email, data.Avatar, data.AccessToken, data.ExpireIn, data.RefreshToken, data.AccessCode, data.UnionId, data.Scope, data.TokenType, data.IdToken, data.MacAlgorithm, data.MacKey, data.Code, data.OauthToken, data.OauthTokenSecret, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.DelFlag, data.Id)
	return err
}

func (m *defaultSysSocialModel) tableName() string {
	return m.table
}
