// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysOperLogFieldNames          = builder.RawFieldNames(&SysOperLog{})
	sysOperLogRows                = strings.Join(sysOperLogFieldNames, ",")
	sysOperLogRowsExpectAutoSet   = strings.Join(stringx.Remove(sysOperLogFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysOperLogRowsWithPlaceHolder = strings.Join(stringx.Remove(sysOperLogFieldNames, "`oper_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysOperLogModel interface {
		Insert(ctx context.Context, data *SysOperLog) (sql.Result, error)
		FindOne(ctx context.Context, operId int64) (*SysOperLog, error)
		Update(ctx context.Context, data *SysOperLog) error
		Delete(ctx context.Context, operId int64) error
	}

	defaultSysOperLogModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysOperLog struct {
		OperId        int64        `db:"oper_id"`        // 日志主键
		TenantId      string       `db:"tenant_id"`      // 租户编号
		Title         string       `db:"title"`          // 模块标题
		BusinessType  int64        `db:"business_type"`  // 业务类型（0其它 1新增 2修改 3删除）
		Method        string       `db:"method"`         // 方法名称
		RequestMethod string       `db:"request_method"` // 请求方式
		OperatorType  int64        `db:"operator_type"`  // 操作类别（0其它 1后台用户 2手机端用户）
		OperName      string       `db:"oper_name"`      // 操作人员
		DeptName      string       `db:"dept_name"`      // 部门名称
		OperUrl       string       `db:"oper_url"`       // 请求URL
		OperIp        string       `db:"oper_ip"`        // 主机地址
		OperLocation  string       `db:"oper_location"`  // 操作地点
		OperParam     string       `db:"oper_param"`     // 请求参数
		JsonResult    string       `db:"json_result"`    // 返回参数
		Status        int64        `db:"status"`         // 操作状态（0正常 1异常）
		ErrorMsg      string       `db:"error_msg"`      // 错误消息
		OperTime      sql.NullTime `db:"oper_time"`      // 操作时间
		CostTime      int64        `db:"cost_time"`      // 消耗时间
	}
)

func newSysOperLogModel(conn sqlx.SqlConn) *defaultSysOperLogModel {
	return &defaultSysOperLogModel{
		conn:  conn,
		table: "`sys_oper_log`",
	}
}

func (m *defaultSysOperLogModel) Delete(ctx context.Context, operId int64) error {
	query := fmt.Sprintf("delete from %s where `oper_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, operId)
	return err
}

func (m *defaultSysOperLogModel) FindOne(ctx context.Context, operId int64) (*SysOperLog, error) {
	query := fmt.Sprintf("select %s from %s where `oper_id` = ? limit 1", sysOperLogRows, m.table)
	var resp SysOperLog
	err := m.conn.QueryRowCtx(ctx, &resp, query, operId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysOperLogModel) Insert(ctx context.Context, data *SysOperLog) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysOperLogRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OperId, data.TenantId, data.Title, data.BusinessType, data.Method, data.RequestMethod, data.OperatorType, data.OperName, data.DeptName, data.OperUrl, data.OperIp, data.OperLocation, data.OperParam, data.JsonResult, data.Status, data.ErrorMsg, data.OperTime, data.CostTime)
	return ret, err
}

func (m *defaultSysOperLogModel) Update(ctx context.Context, data *SysOperLog) error {
	query := fmt.Sprintf("update %s set %s where `oper_id` = ?", m.table, sysOperLogRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.Title, data.BusinessType, data.Method, data.RequestMethod, data.OperatorType, data.OperName, data.DeptName, data.OperUrl, data.OperIp, data.OperLocation, data.OperParam, data.JsonResult, data.Status, data.ErrorMsg, data.OperTime, data.CostTime, data.OperId)
	return err
}

func (m *defaultSysOperLogModel) tableName() string {
	return m.table
}
