// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDictTypeFieldNames          = builder.RawFieldNames(&SysDictType{})
	sysDictTypeRows                = strings.Join(sysDictTypeFieldNames, ",")
	sysDictTypeRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDictTypeFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysDictTypeRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDictTypeFieldNames, "`dict_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysDictTypeModel interface {
		Insert(ctx context.Context, data *SysDictType) (sql.Result, error)
		FindOne(ctx context.Context, dictId int64) (*SysDictType, error)
		FindOneByTenantIdDictType(ctx context.Context, tenantId string, dictType string) (*SysDictType, error)
		Update(ctx context.Context, data *SysDictType) error
		Delete(ctx context.Context, dictId int64) error
	}

	defaultSysDictTypeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysDictType struct {
		DictId     int64          `db:"dict_id"`     // 字典主键
		TenantId   string         `db:"tenant_id"`   // 租户编号
		DictName   string         `db:"dict_name"`   // 字典名称
		DictType   string         `db:"dict_type"`   // 字典类型
		CreateDept sql.NullInt64  `db:"create_dept"` // 创建部门
		CreateBy   sql.NullInt64  `db:"create_by"`   // 创建者
		CreateTime sql.NullTime   `db:"create_time"` // 创建时间
		UpdateBy   sql.NullInt64  `db:"update_by"`   // 更新者
		UpdateTime sql.NullTime   `db:"update_time"` // 更新时间
		Remark     sql.NullString `db:"remark"`      // 备注
	}
)

func newSysDictTypeModel(conn sqlx.SqlConn) *defaultSysDictTypeModel {
	return &defaultSysDictTypeModel{
		conn:  conn,
		table: "`sys_dict_type`",
	}
}

func (m *defaultSysDictTypeModel) Delete(ctx context.Context, dictId int64) error {
	query := fmt.Sprintf("delete from %s where `dict_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, dictId)
	return err
}

func (m *defaultSysDictTypeModel) FindOne(ctx context.Context, dictId int64) (*SysDictType, error) {
	query := fmt.Sprintf("select %s from %s where `dict_id` = ? limit 1", sysDictTypeRows, m.table)
	var resp SysDictType
	err := m.conn.QueryRowCtx(ctx, &resp, query, dictId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictTypeModel) FindOneByTenantIdDictType(ctx context.Context, tenantId string, dictType string) (*SysDictType, error) {
	var resp SysDictType
	query := fmt.Sprintf("select %s from %s where `tenant_id` = ? and `dict_type` = ? limit 1", sysDictTypeRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, tenantId, dictType)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDictTypeModel) Insert(ctx context.Context, data *SysDictType) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysDictTypeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DictId, data.TenantId, data.DictName, data.DictType, data.CreateDept, data.CreateBy, data.UpdateBy, data.Remark)
	return ret, err
}

func (m *defaultSysDictTypeModel) Update(ctx context.Context, newData *SysDictType) error {
	query := fmt.Sprintf("update %s set %s where `dict_id` = ?", m.table, sysDictTypeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.TenantId, newData.DictName, newData.DictType, newData.CreateDept, newData.CreateBy, newData.UpdateBy, newData.Remark, newData.DictId)
	return err
}

func (m *defaultSysDictTypeModel) tableName() string {
	return m.table
}
