// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysUserRoleFieldNames          = builder.RawFieldNames(&SysUserRole{})
	sysUserRoleRows                = strings.Join(sysUserRoleFieldNames, ",")
	sysUserRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(sysUserRoleFieldNames, "`=`"), ",")
	sysUserRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(sysUserRoleFieldNames, "`user_id`", "`role_id`", "`=`"), "=?,") + "=?"
)

type (
	sysUserRoleModel interface {
		Insert(ctx context.Context, data *SysUserRole) (sql.Result, error)
		FindOne(ctx context.Context, userId int64, roleId int64) (*SysUserRole, error)
		Update(ctx context.Context, data *SysUserRole) error
		Delete(ctx context.Context, userId int64, roleId int64) error
	}

	defaultSysUserRoleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysUserRole struct {
		UserId int64 `db:"user_id"` // 用户ID
		RoleId int64 `db:"role_id"` // 角色ID
	}
)

func newSysUserRoleModel(conn sqlx.SqlConn) *defaultSysUserRoleModel {
	return &defaultSysUserRoleModel{
		conn:  conn,
		table: "`sys_user_role`",
	}
}

func (m *defaultSysUserRoleModel) Delete(ctx context.Context, userId int64, roleId int64) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ? and `role_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId, roleId)
	return err
}

func (m *defaultSysUserRoleModel) FindOne(ctx context.Context, userId int64, roleId int64) (*SysUserRole, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `role_id` = ? limit 1", sysUserRoleRows, m.table)
	var resp SysUserRole
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, roleId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserRoleModel) Insert(ctx context.Context, data *SysUserRole) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, sysUserRoleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.RoleId)
	return ret, err
}

func (m *defaultSysUserRoleModel) Update(ctx context.Context, data *SysUserRole) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ? and `role_id` = ?", m.table, sysUserRoleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.RoleId)
	return err
}

func (m *defaultSysUserRoleModel) tableName() string {
	return m.table
}
