// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysDeptFieldNames          = builder.RawFieldNames(&SysDept{})
	sysDeptRows                = strings.Join(sysDeptFieldNames, ",")
	sysDeptRowsExpectAutoSet   = strings.Join(stringx.Remove(sysDeptFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysDeptRowsWithPlaceHolder = strings.Join(stringx.Remove(sysDeptFieldNames, "`dept_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysDeptModel interface {
		Insert(ctx context.Context, data *SysDept) (sql.Result, error)
		FindOne(ctx context.Context, deptId int64) (*SysDept, error)
		Update(ctx context.Context, data *SysDept) error
		Delete(ctx context.Context, deptId int64) error
	}

	defaultSysDeptModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysDept struct {
		DeptId       int64          `db:"dept_id"`       // 部门id
		TenantId     string         `db:"tenant_id"`     // 租户编号
		ParentId     int64          `db:"parent_id"`     // 父部门id
		Ancestors    string         `db:"ancestors"`     // 祖级列表
		DeptName     string         `db:"dept_name"`     // 部门名称
		DeptCategory sql.NullString `db:"dept_category"` // 部门类别编码
		OrderNum     int64          `db:"order_num"`     // 显示顺序
		Leader       sql.NullInt64  `db:"leader"`        // 负责人
		Phone        sql.NullString `db:"phone"`         // 联系电话
		Email        sql.NullString `db:"email"`         // 邮箱
		Status       string         `db:"status"`        // 部门状态（0正常 1停用）
		DelFlag      string         `db:"del_flag"`      // 删除标志（0代表存在 1代表删除）
		CreateDept   sql.NullInt64  `db:"create_dept"`   // 创建部门
		CreateBy     sql.NullInt64  `db:"create_by"`     // 创建者
		CreateTime   sql.NullTime   `db:"create_time"`   // 创建时间
		UpdateBy     sql.NullInt64  `db:"update_by"`     // 更新者
		UpdateTime   sql.NullTime   `db:"update_time"`   // 更新时间
	}
)

func newSysDeptModel(conn sqlx.SqlConn) *defaultSysDeptModel {
	return &defaultSysDeptModel{
		conn:  conn,
		table: "`sys_dept`",
	}
}

func (m *defaultSysDeptModel) Delete(ctx context.Context, deptId int64) error {
	query := fmt.Sprintf("delete from %s where `dept_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, deptId)
	return err
}

func (m *defaultSysDeptModel) FindOne(ctx context.Context, deptId int64) (*SysDept, error) {
	query := fmt.Sprintf("select %s from %s where `dept_id` = ? limit 1", sysDeptRows, m.table)
	var resp SysDept
	err := m.conn.QueryRowCtx(ctx, &resp, query, deptId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysDeptModel) Insert(ctx context.Context, data *SysDept) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysDeptRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.DeptId, data.TenantId, data.ParentId, data.Ancestors, data.DeptName, data.DeptCategory, data.OrderNum, data.Leader, data.Phone, data.Email, data.Status, data.DelFlag, data.CreateDept, data.CreateBy, data.UpdateBy)
	return ret, err
}

func (m *defaultSysDeptModel) Update(ctx context.Context, data *SysDept) error {
	query := fmt.Sprintf("update %s set %s where `dept_id` = ?", m.table, sysDeptRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.ParentId, data.Ancestors, data.DeptName, data.DeptCategory, data.OrderNum, data.Leader, data.Phone, data.Email, data.Status, data.DelFlag, data.CreateDept, data.CreateBy, data.UpdateBy, data.DeptId)
	return err
}

func (m *defaultSysDeptModel) tableName() string {
	return m.table
}
