// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysClientFieldNames          = builder.RawFieldNames(&SysClient{})
	sysClientRows                = strings.Join(sysClientFieldNames, ",")
	sysClientRowsExpectAutoSet   = strings.Join(stringx.Remove(sysClientFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysClientRowsWithPlaceHolder = strings.Join(stringx.Remove(sysClientFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysClientModel interface {
		Insert(ctx context.Context, data *SysClient) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysClient, error)
		Update(ctx context.Context, data *SysClient) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysClientModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysClient struct {
		Id            int64          `db:"id"`             // id
		ClientId      sql.NullString `db:"client_id"`      // 客户端id
		ClientKey     sql.NullString `db:"client_key"`     // 客户端key
		ClientSecret  sql.NullString `db:"client_secret"`  // 客户端秘钥
		GrantType     sql.NullString `db:"grant_type"`     // 授权类型
		DeviceType    sql.NullString `db:"device_type"`    // 设备类型
		ActiveTimeout int64          `db:"active_timeout"` // token活跃超时时间
		Timeout       int64          `db:"timeout"`        // token固定超时
		Status        string         `db:"status"`         // 状态（0正常 1停用）
		DelFlag       string         `db:"del_flag"`       // 删除标志（0代表存在 1代表删除）
		CreateDept    sql.NullInt64  `db:"create_dept"`    // 创建部门
		CreateBy      sql.NullInt64  `db:"create_by"`      // 创建者
		CreateTime    sql.NullTime   `db:"create_time"`    // 创建时间
		UpdateBy      sql.NullInt64  `db:"update_by"`      // 更新者
		UpdateTime    sql.NullTime   `db:"update_time"`    // 更新时间
	}
)

func newSysClientModel(conn sqlx.SqlConn) *defaultSysClientModel {
	return &defaultSysClientModel{
		conn:  conn,
		table: "`sys_client`",
	}
}

func (m *defaultSysClientModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysClientModel) FindOne(ctx context.Context, id int64) (*SysClient, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysClientRows, m.table)
	var resp SysClient
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysClientModel) Insert(ctx context.Context, data *SysClient) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysClientRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ClientId, data.ClientKey, data.ClientSecret, data.GrantType, data.DeviceType, data.ActiveTimeout, data.Timeout, data.Status, data.DelFlag, data.CreateDept, data.CreateBy, data.UpdateBy)
	return ret, err
}

func (m *defaultSysClientModel) Update(ctx context.Context, data *SysClient) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysClientRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ClientId, data.ClientKey, data.ClientSecret, data.GrantType, data.DeviceType, data.ActiveTimeout, data.Timeout, data.Status, data.DelFlag, data.CreateDept, data.CreateBy, data.UpdateBy, data.Id)
	return err
}

func (m *defaultSysClientModel) tableName() string {
	return m.table
}
