// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysOssFieldNames          = builder.RawFieldNames(&SysOss{})
	sysOssRows                = strings.Join(sysOssFieldNames, ",")
	sysOssRowsExpectAutoSet   = strings.Join(stringx.Remove(sysOssFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysOssRowsWithPlaceHolder = strings.Join(stringx.Remove(sysOssFieldNames, "`oss_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysOssModel interface {
		Insert(ctx context.Context, data *SysOss) (sql.Result, error)
		FindOne(ctx context.Context, ossId int64) (*SysOss, error)
		Update(ctx context.Context, data *SysOss) error
		Delete(ctx context.Context, ossId int64) error
	}

	defaultSysOssModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysOss struct {
		OssId        int64          `db:"oss_id"`        // 对象存储主键
		TenantId     string         `db:"tenant_id"`     // 租户编号
		FileName     string         `db:"file_name"`     // 文件名
		OriginalName string         `db:"original_name"` // 原名
		FileSuffix   string         `db:"file_suffix"`   // 文件后缀名
		Url          string         `db:"url"`           // URL地址
		Ext1         sql.NullString `db:"ext1"`          // 扩展字段
		CreateDept   sql.NullInt64  `db:"create_dept"`   // 创建部门
		CreateTime   sql.NullTime   `db:"create_time"`   // 创建时间
		CreateBy     sql.NullInt64  `db:"create_by"`     // 上传人
		UpdateTime   sql.NullTime   `db:"update_time"`   // 更新时间
		UpdateBy     sql.NullInt64  `db:"update_by"`     // 更新人
		Service      string         `db:"service"`       // 服务商
	}
)

func newSysOssModel(conn sqlx.SqlConn) *defaultSysOssModel {
	return &defaultSysOssModel{
		conn:  conn,
		table: "`sys_oss`",
	}
}

func (m *defaultSysOssModel) Delete(ctx context.Context, ossId int64) error {
	query := fmt.Sprintf("delete from %s where `oss_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, ossId)
	return err
}

func (m *defaultSysOssModel) FindOne(ctx context.Context, ossId int64) (*SysOss, error) {
	query := fmt.Sprintf("select %s from %s where `oss_id` = ? limit 1", sysOssRows, m.table)
	var resp SysOss
	err := m.conn.QueryRowCtx(ctx, &resp, query, ossId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysOssModel) Insert(ctx context.Context, data *SysOss) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysOssRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OssId, data.TenantId, data.FileName, data.OriginalName, data.FileSuffix, data.Url, data.Ext1, data.CreateDept, data.CreateBy, data.UpdateBy, data.Service)
	return ret, err
}

func (m *defaultSysOssModel) Update(ctx context.Context, data *SysOss) error {
	query := fmt.Sprintf("update %s set %s where `oss_id` = ?", m.table, sysOssRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.FileName, data.OriginalName, data.FileSuffix, data.Url, data.Ext1, data.CreateDept, data.CreateBy, data.UpdateBy, data.Service, data.OssId)
	return err
}

func (m *defaultSysOssModel) tableName() string {
	return m.table
}
