// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysUserPostFieldNames          = builder.RawFieldNames(&SysUserPost{})
	sysUserPostRows                = strings.Join(sysUserPostFieldNames, ",")
	sysUserPostRowsExpectAutoSet   = strings.Join(stringx.Remove(sysUserPostFieldNames, "`=`"), ",")
	sysUserPostRowsWithPlaceHolder = strings.Join(stringx.Remove(sysUserPostFieldNames, "`user_id`", "`post_id`", "`=`"), "=?,") + "=?"
)

type (
	sysUserPostModel interface {
		Insert(ctx context.Context, data *SysUserPost) (sql.Result, error)
		FindOne(ctx context.Context, userId int64, postId int64) (*SysUserPost, error)
		Update(ctx context.Context, data *SysUserPost) error
		Delete(ctx context.Context, userId int64, postId int64) error
	}

	defaultSysUserPostModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysUserPost struct {
		UserId int64 `db:"user_id"` // 用户ID
		PostId int64 `db:"post_id"` // 岗位ID
	}
)

func newSysUserPostModel(conn sqlx.SqlConn) *defaultSysUserPostModel {
	return &defaultSysUserPostModel{
		conn:  conn,
		table: "`sys_user_post`",
	}
}

func (m *defaultSysUserPostModel) Delete(ctx context.Context, userId int64, postId int64) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ? and `post_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId, postId)
	return err
}

func (m *defaultSysUserPostModel) FindOne(ctx context.Context, userId int64, postId int64) (*SysUserPost, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? and `post_id` = ? limit 1", sysUserPostRows, m.table)
	var resp SysUserPost
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId, postId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserPostModel) Insert(ctx context.Context, data *SysUserPost) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, sysUserPostRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.PostId)
	return ret, err
}

func (m *defaultSysUserPostModel) Update(ctx context.Context, data *SysUserPost) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ? and `post_id` = ?", m.table, sysUserPostRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.PostId)
	return err
}

func (m *defaultSysUserPostModel) tableName() string {
	return m.table
}
