// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysRoleDeptFieldNames          = builder.RawFieldNames(&SysRoleDept{})
	sysRoleDeptRows                = strings.Join(sysRoleDeptFieldNames, ",")
	sysRoleDeptRowsExpectAutoSet   = strings.Join(stringx.Remove(sysRoleDeptFieldNames, "`=`"), ",")
	sysRoleDeptRowsWithPlaceHolder = strings.Join(stringx.Remove(sysRoleDeptFieldNames, "`role_id`", "`dept_id`", "`=`"), "=?,") + "=?"
)

type (
	sysRoleDeptModel interface {
		Insert(ctx context.Context, data *SysRoleDept) (sql.Result, error)
		FindOne(ctx context.Context, roleId int64, deptId int64) (*SysRoleDept, error)
		Update(ctx context.Context, data *SysRoleDept) error
		Delete(ctx context.Context, roleId int64, deptId int64) error
	}

	defaultSysRoleDeptModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysRoleDept struct {
		RoleId int64 `db:"role_id"` // 角色ID
		DeptId int64 `db:"dept_id"` // 部门ID
	}
)

func newSysRoleDeptModel(conn sqlx.SqlConn) *defaultSysRoleDeptModel {
	return &defaultSysRoleDeptModel{
		conn:  conn,
		table: "`sys_role_dept`",
	}
}

func (m *defaultSysRoleDeptModel) Delete(ctx context.Context, roleId int64, deptId int64) error {
	query := fmt.Sprintf("delete from %s where `role_id` = ? and `dept_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, roleId, deptId)
	return err
}

func (m *defaultSysRoleDeptModel) FindOne(ctx context.Context, roleId int64, deptId int64) (*SysRoleDept, error) {
	query := fmt.Sprintf("select %s from %s where `role_id` = ? and `dept_id` = ? limit 1", sysRoleDeptRows, m.table)
	var resp SysRoleDept
	err := m.conn.QueryRowCtx(ctx, &resp, query, roleId, deptId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRoleDeptModel) Insert(ctx context.Context, data *SysRoleDept) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, sysRoleDeptRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.DeptId)
	return ret, err
}

func (m *defaultSysRoleDeptModel) Update(ctx context.Context, data *SysRoleDept) error {
	query := fmt.Sprintf("update %s set %s where `role_id` = ? and `dept_id` = ?", m.table, sysRoleDeptRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.DeptId)
	return err
}

func (m *defaultSysRoleDeptModel) tableName() string {
	return m.table
}
