// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysConfigFieldNames          = builder.RawFieldNames(&SysConfig{})
	sysConfigRows                = strings.Join(sysConfigFieldNames, ",")
	sysConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(sysConfigFieldNames, "`=`"), ",")
	sysConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(sysConfigFieldNames, "`config_id`", "`=`"), "=?,") + "=?"
)

type (
	sysConfigModel interface {
		Insert(ctx context.Context, data *SysConfig) (sql.Result, error)
		FindOne(ctx context.Context, configId int64) (*SysConfig, error)
		Update(ctx context.Context, data *SysConfig) error
		Delete(ctx context.Context, configId int64) error
	}

	defaultSysConfigModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysConfig struct {
		ConfigId    int64          `db:"config_id"`    // 参数主键
		TenantId    string         `db:"tenant_id"`    // 租户编号
		ConfigName  string         `db:"config_name"`  // 参数名称
		ConfigKey   string         `db:"config_key"`   // 参数键名
		ConfigValue string         `db:"config_value"` // 参数键值
		ConfigType  string         `db:"config_type"`  // 系统内置（Y是 N否）
		CreateDept  sql.NullInt64  `db:"create_dept"`  // 创建部门
		CreateBy    sql.NullInt64  `db:"create_by"`    // 创建者
		CreateTime  sql.NullTime   `db:"create_time"`  // 创建时间
		UpdateBy    sql.NullInt64  `db:"update_by"`    // 更新者
		UpdateTime  sql.NullTime   `db:"update_time"`  // 更新时间
		Remark      sql.NullString `db:"remark"`       // 备注
	}
)

func newSysConfigModel(conn sqlx.SqlConn) *defaultSysConfigModel {
	return &defaultSysConfigModel{
		conn:  conn,
		table: "`sys_config`",
	}
}

func (m *defaultSysConfigModel) Delete(ctx context.Context, configId int64) error {
	query := fmt.Sprintf("delete from %s where `config_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, configId)
	return err
}

func (m *defaultSysConfigModel) FindOne(ctx context.Context, configId int64) (*SysConfig, error) {
	query := fmt.Sprintf("select %s from %s where `config_id` = ? limit 1", sysConfigRows, m.table)
	var resp SysConfig
	err := m.conn.QueryRowCtx(ctx, &resp, query, configId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysConfigModel) Insert(ctx context.Context, data *SysConfig) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysConfigRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.ConfigId, data.TenantId, data.ConfigName, data.ConfigKey, data.ConfigValue, data.ConfigType, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.Remark)
	return ret, err
}

func (m *defaultSysConfigModel) Update(ctx context.Context, data *SysConfig) error {
	query := fmt.Sprintf("update %s set %s where `config_id` = ?", m.table, sysConfigRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.ConfigName, data.ConfigKey, data.ConfigValue, data.ConfigType, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.Remark, data.ConfigId)
	return err
}

func (m *defaultSysConfigModel) tableName() string {
	return m.table
}
