// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysOssConfigFieldNames          = builder.RawFieldNames(&SysOssConfig{})
	sysOssConfigRows                = strings.Join(sysOssConfigFieldNames, ",")
	sysOssConfigRowsExpectAutoSet   = strings.Join(stringx.Remove(sysOssConfigFieldNames, "`=`"), ",")
	sysOssConfigRowsWithPlaceHolder = strings.Join(stringx.Remove(sysOssConfigFieldNames, "`oss_config_id`", "`=`"), "=?,") + "=?"
)

type (
	sysOssConfigModel interface {
		Insert(ctx context.Context, data *SysOssConfig) (sql.Result, error)
		FindOne(ctx context.Context, ossConfigId int64) (*SysOssConfig, error)
		Update(ctx context.Context, data *SysOssConfig) error
		Delete(ctx context.Context, ossConfigId int64) error
	}

	defaultSysOssConfigModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysOssConfig struct {
		OssConfigId  int64          `db:"oss_config_id"` // 主键
		TenantId     string         `db:"tenant_id"`     // 租户编号
		ConfigKey    string         `db:"config_key"`    // 配置key
		AccessKey    string         `db:"access_key"`    // accessKey
		SecretKey    string         `db:"secret_key"`    // 秘钥
		BucketName   string         `db:"bucket_name"`   // 桶名称
		Prefix       string         `db:"prefix"`        // 前缀
		Endpoint     string         `db:"endpoint"`      // 访问站点
		Domain       string         `db:"domain"`        // 自定义域名
		IsHttps      string         `db:"is_https"`      // 是否https（Y=是,N=否）
		Region       string         `db:"region"`        // 域
		AccessPolicy string         `db:"access_policy"` // 桶权限类型(0=private 1=public 2=custom)
		Status       string         `db:"status"`        // 是否默认（0=是,1=否）
		Ext1         string         `db:"ext1"`          // 扩展字段
		CreateDept   sql.NullInt64  `db:"create_dept"`   // 创建部门
		CreateBy     sql.NullInt64  `db:"create_by"`     // 创建者
		CreateTime   sql.NullTime   `db:"create_time"`   // 创建时间
		UpdateBy     sql.NullInt64  `db:"update_by"`     // 更新者
		UpdateTime   sql.NullTime   `db:"update_time"`   // 更新时间
		Remark       sql.NullString `db:"remark"`        // 备注
	}
)

func newSysOssConfigModel(conn sqlx.SqlConn) *defaultSysOssConfigModel {
	return &defaultSysOssConfigModel{
		conn:  conn,
		table: "`sys_oss_config`",
	}
}

func (m *defaultSysOssConfigModel) Delete(ctx context.Context, ossConfigId int64) error {
	query := fmt.Sprintf("delete from %s where `oss_config_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, ossConfigId)
	return err
}

func (m *defaultSysOssConfigModel) FindOne(ctx context.Context, ossConfigId int64) (*SysOssConfig, error) {
	query := fmt.Sprintf("select %s from %s where `oss_config_id` = ? limit 1", sysOssConfigRows, m.table)
	var resp SysOssConfig
	err := m.conn.QueryRowCtx(ctx, &resp, query, ossConfigId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysOssConfigModel) Insert(ctx context.Context, data *SysOssConfig) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysOssConfigRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.OssConfigId, data.TenantId, data.ConfigKey, data.AccessKey, data.SecretKey, data.BucketName, data.Prefix, data.Endpoint, data.Domain, data.IsHttps, data.Region, data.AccessPolicy, data.Status, data.Ext1, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.Remark)
	return ret, err
}

func (m *defaultSysOssConfigModel) Update(ctx context.Context, data *SysOssConfig) error {
	query := fmt.Sprintf("update %s set %s where `oss_config_id` = ?", m.table, sysOssConfigRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.ConfigKey, data.AccessKey, data.SecretKey, data.BucketName, data.Prefix, data.Endpoint, data.Domain, data.IsHttps, data.Region, data.AccessPolicy, data.Status, data.Ext1, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.Remark, data.OssConfigId)
	return err
}

func (m *defaultSysOssConfigModel) tableName() string {
	return m.table
}
