// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysTenantFieldNames          = builder.RawFieldNames(&SysTenant{})
	sysTenantRows                = strings.Join(sysTenantFieldNames, ",")
	sysTenantRowsExpectAutoSet   = strings.Join(stringx.Remove(sysTenantFieldNames, "`=`"), ",")
	sysTenantRowsWithPlaceHolder = strings.Join(stringx.Remove(sysTenantFieldNames, "`id`", "`=`"), "=?,") + "=?"
)

type (
	sysTenantModel interface {
		Insert(ctx context.Context, data *SysTenant) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*SysTenant, error)
		Update(ctx context.Context, data *SysTenant) error
		Delete(ctx context.Context, id int64) error
	}

	defaultSysTenantModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysTenant struct {
		Id              int64          `db:"id"`                // id
		TenantId        string         `db:"tenant_id"`         // 租户编号
		ContactUserName sql.NullString `db:"contact_user_name"` // 联系人
		ContactPhone    sql.NullString `db:"contact_phone"`     // 联系电话
		CompanyName     sql.NullString `db:"company_name"`      // 企业名称
		LicenseNumber   sql.NullString `db:"license_number"`    // 统一社会信用代码
		Address         sql.NullString `db:"address"`           // 地址
		Intro           sql.NullString `db:"intro"`             // 企业简介
		Domain          sql.NullString `db:"domain"`            // 域名
		Remark          sql.NullString `db:"remark"`            // 备注
		PackageId       sql.NullInt64  `db:"package_id"`        // 租户套餐编号
		ExpireTime      sql.NullTime   `db:"expire_time"`       // 过期时间
		AccountCount    int64          `db:"account_count"`     // 用户数量（-1不限制）
		Status          string         `db:"status"`            // 租户状态（0正常 1停用）
		DelFlag         string         `db:"del_flag"`          // 删除标志（0代表存在 1代表删除）
		CreateDept      sql.NullInt64  `db:"create_dept"`       // 创建部门
		CreateBy        sql.NullInt64  `db:"create_by"`         // 创建者
		CreateTime      sql.NullTime   `db:"create_time"`       // 创建时间
		UpdateBy        sql.NullInt64  `db:"update_by"`         // 更新者
		UpdateTime      sql.NullTime   `db:"update_time"`       // 更新时间
	}
)

func newSysTenantModel(conn sqlx.SqlConn) *defaultSysTenantModel {
	return &defaultSysTenantModel{
		conn:  conn,
		table: "`sys_tenant`",
	}
}

func (m *defaultSysTenantModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSysTenantModel) FindOne(ctx context.Context, id int64) (*SysTenant, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", sysTenantRows, m.table)
	var resp SysTenant
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysTenantModel) Insert(ctx context.Context, data *SysTenant) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysTenantRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.TenantId, data.ContactUserName, data.ContactPhone, data.CompanyName, data.LicenseNumber, data.Address, data.Intro, data.Domain, data.Remark, data.PackageId, data.ExpireTime, data.AccountCount, data.Status, data.DelFlag, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime)
	return ret, err
}

func (m *defaultSysTenantModel) Update(ctx context.Context, data *SysTenant) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, sysTenantRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.ContactUserName, data.ContactPhone, data.CompanyName, data.LicenseNumber, data.Address, data.Intro, data.Domain, data.Remark, data.PackageId, data.ExpireTime, data.AccountCount, data.Status, data.DelFlag, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.Id)
	return err
}

func (m *defaultSysTenantModel) tableName() string {
	return m.table
}
