// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysLogininforFieldNames          = builder.RawFieldNames(&SysLogininfor{})
	sysLogininforRows                = strings.Join(sysLogininforFieldNames, ",")
	sysLogininforRowsExpectAutoSet   = strings.Join(stringx.Remove(sysLogininforFieldNames, "`=`"), ",")
	sysLogininforRowsWithPlaceHolder = strings.Join(stringx.Remove(sysLogininforFieldNames, "`info_id`", "`=`"), "=?,") + "=?"
)

type (
	sysLogininforModel interface {
		Insert(ctx context.Context, data *SysLogininfor) (sql.Result, error)
		FindOne(ctx context.Context, infoId int64) (*SysLogininfor, error)
		Update(ctx context.Context, data *SysLogininfor) error
		Delete(ctx context.Context, infoId int64) error
	}

	defaultSysLogininforModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysLogininfor struct {
		InfoId        int64        `db:"info_id"`        // 访问ID
		TenantId      string       `db:"tenant_id"`      // 租户编号
		UserName      string       `db:"user_name"`      // 用户账号
		ClientKey     string       `db:"client_key"`     // 客户端
		DeviceType    string       `db:"device_type"`    // 设备类型
		Ipaddr        string       `db:"ipaddr"`         // 登录IP地址
		LoginLocation string       `db:"login_location"` // 登录地点
		Browser       string       `db:"browser"`        // 浏览器类型
		Os            string       `db:"os"`             // 操作系统
		Status        string       `db:"status"`         // 登录状态（0成功 1失败）
		Msg           string       `db:"msg"`            // 提示消息
		LoginTime     sql.NullTime `db:"login_time"`     // 访问时间
	}
)

func newSysLogininforModel(conn sqlx.SqlConn) *defaultSysLogininforModel {
	return &defaultSysLogininforModel{
		conn:  conn,
		table: "`sys_logininfor`",
	}
}

func (m *defaultSysLogininforModel) Delete(ctx context.Context, infoId int64) error {
	query := fmt.Sprintf("delete from %s where `info_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, infoId)
	return err
}

func (m *defaultSysLogininforModel) FindOne(ctx context.Context, infoId int64) (*SysLogininfor, error) {
	query := fmt.Sprintf("select %s from %s where `info_id` = ? limit 1", sysLogininforRows, m.table)
	var resp SysLogininfor
	err := m.conn.QueryRowCtx(ctx, &resp, query, infoId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysLogininforModel) Insert(ctx context.Context, data *SysLogininfor) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysLogininforRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.InfoId, data.TenantId, data.UserName, data.ClientKey, data.DeviceType, data.Ipaddr, data.LoginLocation, data.Browser, data.Os, data.Status, data.Msg, data.LoginTime)
	return ret, err
}

func (m *defaultSysLogininforModel) Update(ctx context.Context, data *SysLogininfor) error {
	query := fmt.Sprintf("update %s set %s where `info_id` = ?", m.table, sysLogininforRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.UserName, data.ClientKey, data.DeviceType, data.Ipaddr, data.LoginLocation, data.Browser, data.Os, data.Status, data.Msg, data.LoginTime, data.InfoId)
	return err
}

func (m *defaultSysLogininforModel) tableName() string {
	return m.table
}
