// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysUserFieldNames          = builder.RawFieldNames(&SysUser{})
	sysUserRows                = strings.Join(sysUserFieldNames, ",")
	sysUserRowsExpectAutoSet   = strings.Join(stringx.Remove(sysUserFieldNames, "`=`"), ",")
	sysUserRowsWithPlaceHolder = strings.Join(stringx.Remove(sysUserFieldNames, "`user_id`", "`=`"), "=?,") + "=?"
)

type (
	sysUserModel interface {
		Insert(ctx context.Context, data *SysUser) (sql.Result, error)
		FindOne(ctx context.Context, userId int64) (*SysUser, error)
		Update(ctx context.Context, data *SysUser) error
		Delete(ctx context.Context, userId int64) error
	}

	defaultSysUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysUser struct {
		UserId      int64          `db:"user_id"`     // 用户ID
		TenantId    string         `db:"tenant_id"`   // 租户编号
		DeptId      sql.NullInt64  `db:"dept_id"`     // 部门ID
		UserName    string         `db:"user_name"`   // 用户账号
		NickName    string         `db:"nick_name"`   // 用户昵称
		UserType    string         `db:"user_type"`   // 用户类型（sys_user系统用户）
		Email       string         `db:"email"`       // 用户邮箱
		Phonenumber string         `db:"phonenumber"` // 手机号码
		Sex         string         `db:"sex"`         // 用户性别（0男 1女 2未知）
		Avatar      sql.NullInt64  `db:"avatar"`      // 头像地址
		Password    string         `db:"password"`    // 密码
		Status      string         `db:"status"`      // 帐号状态（0正常 1停用）
		DelFlag     string         `db:"del_flag"`    // 删除标志（0代表存在 1代表删除）
		LoginIp     string         `db:"login_ip"`    // 最后登录IP
		LoginDate   sql.NullTime   `db:"login_date"`  // 最后登录时间
		CreateDept  sql.NullInt64  `db:"create_dept"` // 创建部门
		CreateBy    sql.NullInt64  `db:"create_by"`   // 创建者
		CreateTime  sql.NullTime   `db:"create_time"` // 创建时间
		UpdateBy    sql.NullInt64  `db:"update_by"`   // 更新者
		UpdateTime  sql.NullTime   `db:"update_time"` // 更新时间
		Remark      sql.NullString `db:"remark"`      // 备注
	}
)

func newSysUserModel(conn sqlx.SqlConn) *defaultSysUserModel {
	return &defaultSysUserModel{
		conn:  conn,
		table: "`sys_user`",
	}
}

func (m *defaultSysUserModel) Delete(ctx context.Context, userId int64) error {
	query := fmt.Sprintf("delete from %s where `user_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, userId)
	return err
}

func (m *defaultSysUserModel) FindOne(ctx context.Context, userId int64) (*SysUser, error) {
	query := fmt.Sprintf("select %s from %s where `user_id` = ? limit 1", sysUserRows, m.table)
	var resp SysUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, userId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysUserModel) Insert(ctx context.Context, data *SysUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TenantId, data.DeptId, data.UserName, data.NickName, data.UserType, data.Email, data.Phonenumber, data.Sex, data.Avatar, data.Password, data.Status, data.DelFlag, data.LoginIp, data.LoginDate, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.Remark)
	return ret, err
}

func (m *defaultSysUserModel) Update(ctx context.Context, data *SysUser) error {
	query := fmt.Sprintf("update %s set %s where `user_id` = ?", m.table, sysUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.DeptId, data.UserName, data.NickName, data.UserType, data.Email, data.Phonenumber, data.Sex, data.Avatar, data.Password, data.Status, data.DelFlag, data.LoginIp, data.LoginDate, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.Remark, data.UserId)
	return err
}

func (m *defaultSysUserModel) tableName() string {
	return m.table
}
