// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysTenantPackageFieldNames          = builder.RawFieldNames(&SysTenantPackage{})
	sysTenantPackageRows                = strings.Join(sysTenantPackageFieldNames, ",")
	sysTenantPackageRowsExpectAutoSet   = strings.Join(stringx.Remove(sysTenantPackageFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysTenantPackageRowsWithPlaceHolder = strings.Join(stringx.Remove(sysTenantPackageFieldNames, "`package_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysTenantPackageModel interface {
		Insert(ctx context.Context, data *SysTenantPackage) (sql.Result, error)
		FindOne(ctx context.Context, packageId int64) (*SysTenantPackage, error)
		Update(ctx context.Context, data *SysTenantPackage) error
		Delete(ctx context.Context, packageId int64) error
	}

	defaultSysTenantPackageModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysTenantPackage struct {
		PackageId         int64          `db:"package_id"`          // 租户套餐id
		PackageName       sql.NullString `db:"package_name"`        // 套餐名称
		MenuIds           sql.NullString `db:"menu_ids"`            // 关联菜单id
		Remark            sql.NullString `db:"remark"`              // 备注
		MenuCheckStrictly int64          `db:"menu_check_strictly"` // 菜单树选择项是否关联显示
		Status            string         `db:"status"`              // 状态（0正常 1停用）
		DelFlag           string         `db:"del_flag"`            // 删除标志（0代表存在 1代表删除）
		CreateDept        sql.NullInt64  `db:"create_dept"`         // 创建部门
		CreateBy          sql.NullInt64  `db:"create_by"`           // 创建者
		CreateTime        sql.NullTime   `db:"create_time"`         // 创建时间
		UpdateBy          sql.NullInt64  `db:"update_by"`           // 更新者
		UpdateTime        sql.NullTime   `db:"update_time"`         // 更新时间
	}
)

func newSysTenantPackageModel(conn sqlx.SqlConn) *defaultSysTenantPackageModel {
	return &defaultSysTenantPackageModel{
		conn:  conn,
		table: "`sys_tenant_package`",
	}
}

func (m *defaultSysTenantPackageModel) Delete(ctx context.Context, packageId int64) error {
	query := fmt.Sprintf("delete from %s where `package_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, packageId)
	return err
}

func (m *defaultSysTenantPackageModel) FindOne(ctx context.Context, packageId int64) (*SysTenantPackage, error) {
	query := fmt.Sprintf("select %s from %s where `package_id` = ? limit 1", sysTenantPackageRows, m.table)
	var resp SysTenantPackage
	err := m.conn.QueryRowCtx(ctx, &resp, query, packageId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysTenantPackageModel) Insert(ctx context.Context, data *SysTenantPackage) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysTenantPackageRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PackageId, data.PackageName, data.MenuIds, data.Remark, data.MenuCheckStrictly, data.Status, data.DelFlag, data.CreateDept, data.CreateBy, data.UpdateBy)
	return ret, err
}

func (m *defaultSysTenantPackageModel) Update(ctx context.Context, data *SysTenantPackage) error {
	query := fmt.Sprintf("update %s set %s where `package_id` = ?", m.table, sysTenantPackageRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.PackageName, data.MenuIds, data.Remark, data.MenuCheckStrictly, data.Status, data.DelFlag, data.CreateDept, data.CreateBy, data.UpdateBy, data.PackageId)
	return err
}

func (m *defaultSysTenantPackageModel) tableName() string {
	return m.table
}
