// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysMenuFieldNames          = builder.RawFieldNames(&SysMenu{})
	sysMenuRows                = strings.Join(sysMenuFieldNames, ",")
	sysMenuRowsExpectAutoSet   = strings.Join(stringx.Remove(sysMenuFieldNames, "`=`"), ",")
	sysMenuRowsWithPlaceHolder = strings.Join(stringx.Remove(sysMenuFieldNames, "`menu_id`", "`=`"), "=?,") + "=?"
)

type (
	sysMenuModel interface {
		Insert(ctx context.Context, data *SysMenu) (sql.Result, error)
		FindOne(ctx context.Context, menuId int64) (*SysMenu, error)
		Update(ctx context.Context, data *SysMenu) error
		Delete(ctx context.Context, menuId int64) error
	}

	defaultSysMenuModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysMenu struct {
		MenuId     int64          `db:"menu_id"`     // 菜单ID
		MenuName   string         `db:"menu_name"`   // 菜单名称
		ParentId   int64          `db:"parent_id"`   // 父菜单ID
		OrderNum   int64          `db:"order_num"`   // 显示顺序
		Path       string         `db:"path"`        // 路由地址
		Component  sql.NullString `db:"component"`   // 组件路径
		QueryParam sql.NullString `db:"query_param"` // 路由参数
		IsFrame    int64          `db:"is_frame"`    // 是否为外链（0是 1否）
		IsCache    int64          `db:"is_cache"`    // 是否缓存（0缓存 1不缓存）
		MenuType   string         `db:"menu_type"`   // 菜单类型（M目录 C菜单 F按钮）
		Visible    string         `db:"visible"`     // 显示状态（0显示 1隐藏）
		Status     string         `db:"status"`      // 菜单状态（0正常 1停用）
		Perms      sql.NullString `db:"perms"`       // 权限标识
		Icon       string         `db:"icon"`        // 菜单图标
		CreateDept sql.NullInt64  `db:"create_dept"` // 创建部门
		CreateBy   sql.NullInt64  `db:"create_by"`   // 创建者
		CreateTime sql.NullTime   `db:"create_time"` // 创建时间
		UpdateBy   sql.NullInt64  `db:"update_by"`   // 更新者
		UpdateTime sql.NullTime   `db:"update_time"` // 更新时间
		Remark     string         `db:"remark"`      // 备注
	}
)

func newSysMenuModel(conn sqlx.SqlConn) *defaultSysMenuModel {
	return &defaultSysMenuModel{
		conn:  conn,
		table: "`sys_menu`",
	}
}

func (m *defaultSysMenuModel) Delete(ctx context.Context, menuId int64) error {
	query := fmt.Sprintf("delete from %s where `menu_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, menuId)
	return err
}

func (m *defaultSysMenuModel) FindOne(ctx context.Context, menuId int64) (*SysMenu, error) {
	query := fmt.Sprintf("select %s from %s where `menu_id` = ? limit 1", sysMenuRows, m.table)
	var resp SysMenu
	err := m.conn.QueryRowCtx(ctx, &resp, query, menuId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysMenuModel) Insert(ctx context.Context, data *SysMenu) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysMenuRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.MenuId, data.MenuName, data.ParentId, data.OrderNum, data.Path, data.Component, data.QueryParam, data.IsFrame, data.IsCache, data.MenuType, data.Visible, data.Status, data.Perms, data.Icon, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.Remark)
	return ret, err
}

func (m *defaultSysMenuModel) Update(ctx context.Context, data *SysMenu) error {
	query := fmt.Sprintf("update %s set %s where `menu_id` = ?", m.table, sysMenuRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.MenuName, data.ParentId, data.OrderNum, data.Path, data.Component, data.QueryParam, data.IsFrame, data.IsCache, data.MenuType, data.Visible, data.Status, data.Perms, data.Icon, data.CreateDept, data.CreateBy, data.CreateTime, data.UpdateBy, data.UpdateTime, data.Remark, data.MenuId)
	return err
}

func (m *defaultSysMenuModel) tableName() string {
	return m.table
}
