// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysRoleFieldNames          = builder.RawFieldNames(&SysRole{})
	sysRoleRows                = strings.Join(sysRoleFieldNames, ",")
	sysRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(sysRoleFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(sysRoleFieldNames, "`role_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysRoleModel interface {
		Insert(ctx context.Context, data *SysRole) (sql.Result, error)
		FindOne(ctx context.Context, roleId int64) (*SysRole, error)
		Update(ctx context.Context, data *SysRole) error
		Delete(ctx context.Context, roleId int64) error
	}

	defaultSysRoleModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysRole struct {
		RoleId            int64          `db:"role_id"`             // 角色ID
		TenantId          string         `db:"tenant_id"`           // 租户编号
		RoleName          string         `db:"role_name"`           // 角色名称
		RoleKey           string         `db:"role_key"`            // 角色权限字符串
		RoleSort          int64          `db:"role_sort"`           // 显示顺序
		DataScope         string         `db:"data_scope"`          // 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限 5：仅本人数据权限 6：部门及以下或本人数据权限）
		MenuCheckStrictly int64          `db:"menu_check_strictly"` // 菜单树选择项是否关联显示
		DeptCheckStrictly int64          `db:"dept_check_strictly"` // 部门树选择项是否关联显示
		Status            string         `db:"status"`              // 角色状态（0正常 1停用）
		DelFlag           string         `db:"del_flag"`            // 删除标志（0代表存在 1代表删除）
		CreateDept        sql.NullInt64  `db:"create_dept"`         // 创建部门
		CreateBy          sql.NullInt64  `db:"create_by"`           // 创建者
		CreateTime        sql.NullTime   `db:"create_time"`         // 创建时间
		UpdateBy          sql.NullInt64  `db:"update_by"`           // 更新者
		UpdateTime        sql.NullTime   `db:"update_time"`         // 更新时间
		Remark            sql.NullString `db:"remark"`              // 备注
	}
)

func newSysRoleModel(conn sqlx.SqlConn) *defaultSysRoleModel {
	return &defaultSysRoleModel{
		conn:  conn,
		table: "`sys_role`",
	}
}

func (m *defaultSysRoleModel) Delete(ctx context.Context, roleId int64) error {
	query := fmt.Sprintf("delete from %s where `role_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, roleId)
	return err
}

func (m *defaultSysRoleModel) FindOne(ctx context.Context, roleId int64) (*SysRole, error) {
	query := fmt.Sprintf("select %s from %s where `role_id` = ? limit 1", sysRoleRows, m.table)
	var resp SysRole
	err := m.conn.QueryRowCtx(ctx, &resp, query, roleId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysRoleModel) Insert(ctx context.Context, data *SysRole) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysRoleRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.RoleId, data.TenantId, data.RoleName, data.RoleKey, data.RoleSort, data.DataScope, data.MenuCheckStrictly, data.DeptCheckStrictly, data.Status, data.DelFlag, data.CreateDept, data.CreateBy, data.UpdateBy, data.Remark)
	return ret, err
}

func (m *defaultSysRoleModel) Update(ctx context.Context, data *SysRole) error {
	query := fmt.Sprintf("update %s set %s where `role_id` = ?", m.table, sysRoleRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.RoleName, data.RoleKey, data.RoleSort, data.DataScope, data.MenuCheckStrictly, data.DeptCheckStrictly, data.Status, data.DelFlag, data.CreateDept, data.CreateBy, data.UpdateBy, data.Remark, data.RoleId)
	return err
}

func (m *defaultSysRoleModel) tableName() string {
	return m.table
}
