// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysNoticeFieldNames          = builder.RawFieldNames(&SysNotice{})
	sysNoticeRows                = strings.Join(sysNoticeFieldNames, ",")
	sysNoticeRowsExpectAutoSet   = strings.Join(stringx.Remove(sysNoticeFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysNoticeRowsWithPlaceHolder = strings.Join(stringx.Remove(sysNoticeFieldNames, "`notice_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysNoticeModel interface {
		Insert(ctx context.Context, data *SysNotice) (sql.Result, error)
		FindOne(ctx context.Context, noticeId int64) (*SysNotice, error)
		Update(ctx context.Context, data *SysNotice) error
		Delete(ctx context.Context, noticeId int64) error
	}

	defaultSysNoticeModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysNotice struct {
		NoticeId      int64          `db:"notice_id"`      // 公告ID
		TenantId      string         `db:"tenant_id"`      // 租户编号
		NoticeTitle   string         `db:"notice_title"`   // 公告标题
		NoticeType    string         `db:"notice_type"`    // 公告类型（1通知 2公告）
		NoticeContent sql.NullString `db:"notice_content"` // 公告内容
		Status        string         `db:"status"`         // 公告状态（0正常 1关闭）
		CreateDept    sql.NullInt64  `db:"create_dept"`    // 创建部门
		CreateBy      sql.NullInt64  `db:"create_by"`      // 创建者
		CreateTime    sql.NullTime   `db:"create_time"`    // 创建时间
		UpdateBy      sql.NullInt64  `db:"update_by"`      // 更新者
		UpdateTime    sql.NullTime   `db:"update_time"`    // 更新时间
		Remark        sql.NullString `db:"remark"`         // 备注
	}
)

func newSysNoticeModel(conn sqlx.SqlConn) *defaultSysNoticeModel {
	return &defaultSysNoticeModel{
		conn:  conn,
		table: "`sys_notice`",
	}
}

func (m *defaultSysNoticeModel) Delete(ctx context.Context, noticeId int64) error {
	query := fmt.Sprintf("delete from %s where `notice_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, noticeId)
	return err
}

func (m *defaultSysNoticeModel) FindOne(ctx context.Context, noticeId int64) (*SysNotice, error) {
	query := fmt.Sprintf("select %s from %s where `notice_id` = ? limit 1", sysNoticeRows, m.table)
	var resp SysNotice
	err := m.conn.QueryRowCtx(ctx, &resp, query, noticeId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysNoticeModel) Insert(ctx context.Context, data *SysNotice) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysNoticeRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.NoticeId, data.TenantId, data.NoticeTitle, data.NoticeType, data.NoticeContent, data.Status, data.CreateDept, data.CreateBy, data.UpdateBy, data.Remark)
	return ret, err
}

func (m *defaultSysNoticeModel) Update(ctx context.Context, data *SysNotice) error {
	query := fmt.Sprintf("update %s set %s where `notice_id` = ?", m.table, sysNoticeRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.NoticeTitle, data.NoticeType, data.NoticeContent, data.Status, data.CreateDept, data.CreateBy, data.UpdateBy, data.Remark, data.NoticeId)
	return err
}

func (m *defaultSysNoticeModel) tableName() string {
	return m.table
}
