// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package sys

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	sysPostFieldNames          = builder.RawFieldNames(&SysPost{})
	sysPostRows                = strings.Join(sysPostFieldNames, ",")
	sysPostRowsExpectAutoSet   = strings.Join(stringx.Remove(sysPostFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	sysPostRowsWithPlaceHolder = strings.Join(stringx.Remove(sysPostFieldNames, "`post_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	sysPostModel interface {
		Insert(ctx context.Context, data *SysPost) (sql.Result, error)
		FindOne(ctx context.Context, postId int64) (*SysPost, error)
		Update(ctx context.Context, data *SysPost) error
		Delete(ctx context.Context, postId int64) error
	}

	defaultSysPostModel struct {
		conn  sqlx.SqlConn
		table string
	}

	SysPost struct {
		PostId       int64          `db:"post_id"`       // 岗位ID
		TenantId     string         `db:"tenant_id"`     // 租户编号
		DeptId       int64          `db:"dept_id"`       // 部门id
		PostCode     string         `db:"post_code"`     // 岗位编码
		PostCategory sql.NullString `db:"post_category"` // 岗位类别编码
		PostName     string         `db:"post_name"`     // 岗位名称
		PostSort     int64          `db:"post_sort"`     // 显示顺序
		Status       string         `db:"status"`        // 状态（0正常 1停用）
		CreateDept   sql.NullInt64  `db:"create_dept"`   // 创建部门
		CreateBy     sql.NullInt64  `db:"create_by"`     // 创建者
		CreateTime   sql.NullTime   `db:"create_time"`   // 创建时间
		UpdateBy     sql.NullInt64  `db:"update_by"`     // 更新者
		UpdateTime   sql.NullTime   `db:"update_time"`   // 更新时间
		Remark       sql.NullString `db:"remark"`        // 备注
	}
)

func newSysPostModel(conn sqlx.SqlConn) *defaultSysPostModel {
	return &defaultSysPostModel{
		conn:  conn,
		table: "`sys_post`",
	}
}

func (m *defaultSysPostModel) Delete(ctx context.Context, postId int64) error {
	query := fmt.Sprintf("delete from %s where `post_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, postId)
	return err
}

func (m *defaultSysPostModel) FindOne(ctx context.Context, postId int64) (*SysPost, error) {
	query := fmt.Sprintf("select %s from %s where `post_id` = ? limit 1", sysPostRows, m.table)
	var resp SysPost
	err := m.conn.QueryRowCtx(ctx, &resp, query, postId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultSysPostModel) Insert(ctx context.Context, data *SysPost) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, sysPostRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.PostId, data.TenantId, data.DeptId, data.PostCode, data.PostCategory, data.PostName, data.PostSort, data.Status, data.CreateDept, data.CreateBy, data.UpdateBy, data.Remark)
	return ret, err
}

func (m *defaultSysPostModel) Update(ctx context.Context, data *SysPost) error {
	query := fmt.Sprintf("update %s set %s where `post_id` = ?", m.table, sysPostRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.TenantId, data.DeptId, data.PostCode, data.PostCategory, data.PostName, data.PostSort, data.Status, data.CreateDept, data.CreateBy, data.UpdateBy, data.Remark, data.PostId)
	return err
}

func (m *defaultSysPostModel) tableName() string {
	return m.table
}
